export const desktopCopy = {
  en: {
    edition: "Personal edition",
    work: "Work",
    about: "About",
    research: "Research",
    contact: "Contact",
    desktop: "Desktop",
    collection: "THE DISK COLLECTION",
    insert: "Choose a disk to load ↓",
    reboot: "REBOOT",
    rebootLabel: "Replay computer boot animation",
    focus: "Expand the screen ↗",
    unfocus: "Back to the desk ↙",
    close: "Close window",
    ready: "Ready. Insert a project disk.",
    loaded: "Disk loaded",
    reading: "Reading disk",
    restarting: "Restarting the computer.",
    desktopReady: "Desktop ready.",
    boot: [
      "BALLOUCH PERSONAL COMPUTER\nPersonal edition",
      "Mounting selected work…",
      "Loading experience & research…",
      "Desktop ready.",
    ],
    skip: "Skip boot ↗",
    hello: "HELLO, WORLD.",
    welcome: "I’m Mohamed.\nI make AI useful.",
    intro:
      "From document assistants to multimodal applications, I turn ideas into working systems.",
    openWork: "Open my work ↗",
    selected: "PROJECT DIRECTORY",
    workTitle: "Things I’ve built.",
    allDisks: "← All disks",
    overview: "Overview",
    toolkit: "Toolkit",
    fullCase: "Read the case study ↗",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    projects: "projects",
    aboutLabel: "THE PERSON AT THE KEYBOARD",
    aboutTitle: "Engineer. Consultant.\nAlways curious.",
    aboutIntro:
      "AI engineering across consulting, production machine learning and applied research.",
    fullExperience: "Explore my experience ↓",
    researchLabel: "RESEARCH & LEARNING",
    researchTitle: "Still asking\nbetter questions.",
    researchIntro:
      "PhD candidate at INPT. Research into learning, forecasting and the coordination of industrial systems.",
    fullResearch: "Publications & education ↓",
    contactLabel: "LET’S BUILD SOMETHING",
    contactTitle: "A new idea?\nLet’s talk.",
    choose: "Choose an app to begin.",
    footer: "OLD-SCHOOL HARDWARE. PRESENT-DAY IDEAS.",
    hardware: "PERSONAL SYSTEM",
    base: "IDEAS / WORK / REPEAT",
    insertLabel: "Insert project disk",
    keyboard: "Portfolio keyboard",
    computer: "Interactive vintage desktop",
    apps: "Computer applications",
    window: "Portfolio window",
    drive: "Project disk drive",
    heroIntro:
      "AI engineer & GenAI consultant.\nBuilt with curiosity.\nBased in Casablanca.",
    disks: {
      agents: ["01 / ENTERPRISE", "Agents at work.", "Exakis Nelite"],
      "insurance-rag": [
        "02 / KNOWLEDGE",
        "Answers, with evidence.",
        "DXC Technology",
      ],
      chart: [
        "03 / MULTIMODAL",
        "Charts, in plain words.",
        "Chart intelligence",
      ],
    },
  },
  fr: {
    edition: "Édition personnelle",
    work: "Projets",
    about: "À propos",
    research: "Recherche",
    contact: "Contact",
    desktop: "Bureau",
    collection: "LA COLLECTION DE DISQUETTES",
    insert: "Choisissez une disquette ↓",
    reboot: "RELANCER",
    rebootLabel: "Rejouer le démarrage de l’ordinateur",
    focus: "Agrandir l’écran ↗",
    unfocus: "Retour à l’ordinateur ↙",
    close: "Fermer la fenêtre",
    ready: "Prêt. Insérez une disquette.",
    loaded: "Disquette chargée",
    reading: "Lecture de la disquette",
    restarting: "Redémarrage de l’ordinateur.",
    desktopReady: "Bureau prêt.",
    boot: [
      "ORDINATEUR PERSONNEL BALLOUCH\nÉdition personnelle",
      "Chargement des réalisations…",
      "Chargement du parcours et des recherches…",
      "Bureau prêt.",
    ],
    skip: "Passer le démarrage ↗",
    hello: "BONJOUR, LE MONDE.",
    welcome: "Moi, c’est Mohamed.\nJe rends l’IA utile.",
    intro:
      "Des assistants documentaires aux applications multimodales, je transforme les idées en systèmes utilisables.",
    openWork: "Ouvrir mes projets ↗",
    selected: "RÉPERTOIRE DES PROJETS",
    workTitle: "Ce que j’ai construit.",
    allDisks: "← Les disquettes",
    overview: "Aperçu",
    toolkit: "Outils",
    fullCase: "Explorer le projet ↗",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    of: "sur",
    projects: "projets",
    aboutLabel: "LA PERSONNE AU CLAVIER",
    aboutTitle: "Ingénieur. Consultant.\nToujours curieux.",
    aboutIntro:
      "L’ingénierie IA entre conseil, machine learning en production et recherche appliquée.",
    fullExperience: "Découvrir mon parcours ↓",
    researchLabel: "RECHERCHE & FORMATION",
    researchTitle: "Toujours de\nnouvelles questions.",
    researchIntro:
      "Doctorant à l’INPT. Recherche sur l’apprentissage, la prévision et la coordination des systèmes industriels.",
    fullResearch: "Publications et formation ↓",
    contactLabel: "CONSTRUISONS QUELQUE CHOSE",
    contactTitle: "Une nouvelle idée ?\nParlons-en.",
    choose: "Ouvrez une application.",
    footer: "UN ORDINATEUR D’HIER. DES IDÉES D’AUJOURD’HUI.",
    hardware: "SYSTÈME PERSONNEL",
    base: "IDÉES / PROJETS / CURIOSITÉ",
    insertLabel: "Insérer la disquette du projet",
    keyboard: "Clavier du portfolio",
    computer: "Bureau rétro interactif",
    apps: "Applications du bureau",
    window: "Fenêtre du portfolio",
    drive: "Lecteur de disquettes",
    heroIntro:
      "Ingénieur IA et consultant en IA générative.\nGuidé par la curiosité.\nBasé à Casablanca.",
    disks: {
      agents: ["01 / ENTREPRISE", "Des agents en action.", "Exakis Nelite"],
      "insurance-rag": [
        "02 / SAVOIRS",
        "Des réponses sourcées.",
        "DXC Technology",
      ],
      chart: [
        "03 / MULTIMODAL",
        "Comprendre les graphiques.",
        "Analyse visuelle",
      ],
    },
  },
};
